### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by bharat** [software-2/nanoleaf#2]
It looks like `setup.py` is trying to calculate the version by using `git tag`, but from what I can tell (and I am not all that well versed with how `pip` works) the tarball is not a git repo so I get the following error:

`subprocess.CalledProcessError: Command '['git', 'tag', '-l', '--points-at', 'HEAD']' returned non-zero exit status 128`

I'm attaching the complete output below, in case that's helpful. 

```
$ pip -v install nanoleaf --upgrade            
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Collecting nanoleaf
  1 location(s) to search for versions of nanoleaf:
  * https://pypi.python.org/simple/nanoleaf/
  Getting page https://pypi.python.org/simple/nanoleaf/
  Looking up "https://pypi.python.org/simple/nanoleaf/" in the cache
  Current age based on date: 554
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 554
  Analyzing links from page https://pypi.python.org/simple/nanoleaf/
    Skipping link https://pypi.python.org/packages/03/37/667f758f90dce756cbdbe9fbf8d5d147d7ab8ce78767776a5bd9b726fd08/nanoleaf-0.2.2-py3-none-any.whl#md5=216ee4c78ca1d21625656308a6af8f8d (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/08/7d/8e261ed14a486d1dd662a0dc3f2134734ab0df37688de61564815e84206b/nanoleaf-0.1.6-py3-none-any.whl#md5=9a860606bd893e9cd5142b740520f81b (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/0e/94/d62e56755cf11ed96ef713e2d727541704e56dba08b9a6b7ac3cf60b74e7/nanoleaf-0.3.0-py3-none-any.whl#md5=fc0550e1106ac8a603d7b1e4c7242bc5 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/11/37/2a382aa5e8f4d3435fa6439b08a1c287df4e8cac55aae64d967755f29e2f/nanoleaf-0.2.1-py3-none-any.whl#md5=c2d9d361605f8f8cceaa03aa9acdeb1a (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/1f/1f/ae6400896daefd7e5077e0b06da32e12f5392f6d42a8809d22f78484a327/nanoleaf-0.3.3.tar.gz#md5=ec66cb18ab48addb0e44415901b10ef9 (from https://pypi.python.org/simple/nanoleaf/), version: 0.3.3
    Found link https://pypi.python.org/packages/3a/ba/f652ce6384fa92c6c0212369f390e6d68d79ea4f3a3ec67e36324cb90d1a/nanoleaf-0.2.0.tar.gz#md5=9427fabc3111c7d40a65f643dbb947b1 (from https://pypi.python.org/simple/nanoleaf/), version: 0.2.0
    Skipping link https://pypi.python.org/packages/54/1f/c69fda5bb5dc07d61a57b5cfa43bb07c67ace5b6e9ac6f2805f6275e402d/nanoleaf-0.3.3-py3-none-any.whl#md5=dc152ff062c54fe521f2370cebf1281a (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/58/10/b4321bfb49d40365a453de56fce85c344b063f3d5814143f8c0354b73e62/nanoleaf-0.4.0-py3-none-any.whl#md5=23175e2db4a7bacd3290b49857602458 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/61/29/2c9356dd4e7b70ce757967b92a3fe6052166654ea9f1807b46e4e144b057/nanoleaf-0.1.4.tar.gz#md5=3e2393660c1482a26df5a393b7a32c7a (from https://pypi.python.org/simple/nanoleaf/), version: 0.1.4
    Found link https://pypi.python.org/packages/68/b5/f6588d1403c26b1a1b772feea645713266c6922a78f15f3364bb10635fe2/nanoleaf-0.1.3.tar.gz#md5=237bb152c581b577670c417125bd10cf (from https://pypi.python.org/simple/nanoleaf/), version: 0.1.3
    Skipping link https://pypi.python.org/packages/72/a7/3b4ef89d6322970a63f629c3dc169cde26e5dc7cddb7f3a5c74af8d4f674/nanoleaf-0.3.2-py3-none-any.whl#md5=41d0b0918d2fc89e00375966dea6bf92 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/7b/ba/7c24348c8faefd1d8170dcfd2df4da3049f18f27b6970e333b993dd14f3b/nanoleaf-0.2.1.tar.gz#md5=cb84ceec1dd140313260192a74d5fd46 (from https://pypi.python.org/simple/nanoleaf/), version: 0.2.1
    Found link https://pypi.python.org/packages/7e/03/7c7b723a1e18d6c4555aa4d0e9c2d7b6f2c4856f632d8f917ede3bf0fbfa/nanoleaf-0.3.0.tar.gz#md5=bc75c81047543fbcc53c0a1d9f6ce0b8 (from https://pypi.python.org/simple/nanoleaf/), version: 0.3.0
    Found link https://pypi.python.org/packages/83/c3/a860b0960a83ad53aa55d50764205ffe47407aa701b1336611ebdfe70724/nanoleaf-0.1.5.tar.gz#md5=3e0bd9bd7bed35e6c3f4e001601d0145 (from https://pypi.python.org/simple/nanoleaf/), version: 0.1.5
    Skipping link https://pypi.python.org/packages/89/a8/e90430ff0a7022425a2f371c360731212d93a22671812a35b228762c13a2/nanoleaf-0.1.5-py3-none-any.whl#md5=b59acff157edb71f5d8fea7d40dae6c8 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/91/6b/47b5304fe5ebc13570a38e805b14764653368c333aa6d43dc8b6ff8b7679/nanoleaf-0.1.3-py3-none-any.whl#md5=5f10a29cf7377d09d305f75b136f0e43 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/91/7f/8e79dbadbd8df7b959589701909249dc16ca71235c5e367d59a14ea3e88c/nanoleaf-0.3.2.tar.gz#md5=82c0a2c1fe90bd54b9b27b9b741f97f1 (from https://pypi.python.org/simple/nanoleaf/), version: 0.3.2
    Skipping link https://pypi.python.org/packages/9b/eb/d67294afc028620b1ca100f72d0ad2b2d5e62a00779369f56895fae62390/nanoleaf-0.2.0-py3-none-any.whl#md5=e53b54f9d50a771c3f7aa85a6e178aa9 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/9f/2f/39e44744ff3a5a26c943a0bf6c857d80a3186572c08c9373b3214c4aefc5/nanoleaf-0.4.1-py3-none-any.whl#md5=f07275b098339e82990fec19311c9d80 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a5/d8/0929f60ebe0fe249cf35c57e51fc7b97fc9dc2ec529dcb3c28ce3db14899/nanoleaf-0.0.0-py3-none-any.whl#md5=9366800789031310fe6c84055a3dad97 (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/ab/aa/f749e8af9d9b1a9c6844373f27e77e3a4aac29f361f7c6e28c5c04d7ce3c/nanoleaf-0.4.1.tar.gz#md5=5f9477f5b627844049e247890f8eebf4 (from https://pypi.python.org/simple/nanoleaf/), version: 0.4.1
    Found link https://pypi.python.org/packages/b6/08/601883f7486495561d6636dcd881c7d86cbcdc74a57523f980c81e208401/nanoleaf-0.0.0.tar.gz#md5=abe2cf339973a3e1a56b9e9ee7238427 (from https://pypi.python.org/simple/nanoleaf/), version: 0.0.0
    Found link https://pypi.python.org/packages/b7/42/644787be51054ccf33a0a2b0491f463c12278545d64bd50ce236deff58f9/nanoleaf-0.1.6.tar.gz#md5=2df25422b374dbc1c4b310392073f437 (from https://pypi.python.org/simple/nanoleaf/), version: 0.1.6
    Found link https://pypi.python.org/packages/cd/26/de81778352f3f4d6ff5ec7db1e83f21ef73e0a61a05bd49fc5128921c71d/nanoleaf-0.2.2.tar.gz#md5=802fffef5c19f86a43ab167897ea03e9 (from https://pypi.python.org/simple/nanoleaf/), version: 0.2.2
    Found link https://pypi.python.org/packages/cf/eb/b05c1a282283d6c7516e9fab8a2d107d83e1534a6939fe29c4e756b148d8/nanoleaf-0.4.0.tar.gz#md5=b5d92144c07ce74880966ce7477aad44 (from https://pypi.python.org/simple/nanoleaf/), version: 0.4.0
    Skipping link https://pypi.python.org/packages/db/b2/a3b128c17bc4b3ff4113db17f2ef2aa5e4c1d658c3285f9f5fcf659f8c7b/nanoleaf-0.1.4-py3-none-any.whl#md5=fefa6380ff3dcdb74c720c693e13130d (from https://pypi.python.org/simple/nanoleaf/); it is not compatible with this Python
  Using version 0.4.1 (newest of versions: 0.0.0, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.2, 0.3.3, 0.4.0, 0.4.1)
  Looking up "https://pypi.python.org/packages/ab/aa/f749e8af9d9b1a9c6844373f27e77e3a4aac29f361f7c6e28c5c04d7ce3c/nanoleaf-0.4.1.tar.gz" in the cache
  Current age based on date: 554
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 554
  Using cached nanoleaf-0.4.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/ab/aa/f749e8af9d9b1a9c6844373f27e77e3a4aac29f361f7c6e28c5c04d7ce3c/nanoleaf-0.4.1.tar.gz#md5=5f9477f5b627844049e247890f8eebf4 (from https://pypi.python.org/simple/nanoleaf/)
  Running setup.py (path:/tmp/pip-build-BE5V1Q/nanoleaf/setup.py) egg_info for package nanoleaf
    Running command python setup.py egg_info
    fatal: Not a git repository (or any parent up to mount point /tmp)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BE5V1Q/nanoleaf/setup.py", line 4, in <module>
        gitVersion = subprocess.check_output("git tag -l --points-at HEAD".split()).decode('UTF-8').strip()
      File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'tag', '-l', '--points-at', 'HEAD']' returned non-zero exit status 128
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BE5V1Q/nanoleaf/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BE5V1Q/nanoleaf/
```

**Comment by software-2** [comment]
You're using Python 2.7, this library requires Python 3.

`pip3 install nanoleaf`
